// src/components/engine/render.tsx
import React from 'react';
import { View, Text } from '@tarojs/components'
import Page from '../page'

export interface RenderProps {
  body: any,
  data: any,
  callback: any
}

const Render: React.FC<Partial<RenderProps>> = (props) => {
  
  // 注册组件
  const parseComponent = (body: any, data: any, callback: any) => {
    
    return [
      {
        key: 'page',
        component: <Page {...body} />,
      },
      {
        key: 'view',
        component: <View style={{ ...body.style }}>{body.body}</View>,
      },
      {
        key: 'text',
        component: <Text {...body}>{body.body}</Text>,
      },
    ];
  };

  // 渲染组件
  const componentRender = (body: any, data: any, callback: any) => {
    if (body === null || body === undefined) {
      return null;
    }

    if (typeof body === 'string' || typeof body === 'number') {
      return <Text>{body}</Text>;
    }

    let component: any = null;
    let parseComponents = parseComponent(body, data, callback);

    if (body.hasOwnProperty('component')) {
      parseComponents.map((item: any) => {
        if (item.key === body.component) {
          component = item.component;
        }
      });
    } else {
      component = body.map((item: any) => {
        return parseComponents.map(
          (componentItem: any) => {
            if (componentItem.key === item.component) {
              return componentItem.component;
            }
          },
        );
      });
    }

    return component;
  };

  return componentRender(props.body, props.data, props.callback);
}

export default Render;

// src/components/Render.vue
<template>
  <view v-if="typeof body === 'string' || typeof body === 'number'">
    {{body}}
  </view>
  <view v-else-if="body.hasOwnProperty('component')">
    <view v-if="body.component === 'page'">
      <PageContainer>
        <Render :body="body.body" />
      </PageContainer>
    </view>
  </view>
  <view v-else>
    <view v-for="(item,index) in body " :key="index">
      <Render :body="item" />
    </view>
  </view>
</template>

<script lang="ts">
import { reactive, toRefs, h } from 'vue';
import Taro from '@tarojs/taro';
import PageContainer from './PageContainer.vue';

export default {
  name: 'Render',
  props: ['body']
}
</script>
